# cSpell:ignore temurin
# cSpell:ignoreRegExp /-D\w+/
name: Maven Package

on:
  push:
    branches:
      - release-*
      - dev-*

jobs:
  environment:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.env.outputs.env }}
    steps:
      - id: env
        run: |
          if [[ $GITHUB_REF_NAME == release-* ]]; then
            echo "::set-output name=env::prod"
          else
            echo "::set-output name=env::dev"
          fi
      - run: echo "::debug::${{ steps.env.outputs.env }}"

  build:
    runs-on: ubuntu-latest
    needs: environment
    environment:
      name: ${{ needs.environment.outputs.env }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.312+7'
        distribution: 'temurin'

    - name: Set version
      if: needs.environment.outputs.env == 'prod'
      run: mvn -B versions:set -DremoveSnapshot=true -DgenerateBackupPoms=false -DprocessAllModules=true

    - name: Build with Maven
      run: mvn -B -s $GITHUB_WORKSPACE/settings.xml package

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B -s $GITHUB_WORKSPACE/settings.xml deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
